services:
  - type: web
    name: questinvest-pro
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run db:push -- --force
    startCommand: NODE_ENV=production node dist/index.cjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: questinvest-db
          property: connectionString
      - key: VITE_API_URL
        value: https://questinvest-pro.onrender.com
  - type: pserv
    name: questinvest-db
    ipAllowList: []
    plan: free
